### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by leonardofaria** [aur1mas/Wkhtmltopdf#12]
I'm using this class and the images doen't appear. The css support works very well.

I tried use absolute path and relative path but doen't work

**Comment by DimaSerikov** [comment]
For images output change:
`$command = 'xvfb-run  ' . $command;` 
to 
`$command = 'xvfb-run -a -s "-screen 0 640x480x16" ' . $command;`

And then enable the virtalX option:
`$wkhtmltopdf->setRunInVirtualX(true);`
