### ISSUE TITLE
Possibility of deadlock in _exec

### ISSUE THREAD

**Issue by scintill** [aur1mas/Wkhtmltopdf#25]
Today I had an issue where my application hung trying to create a PDF on Linux.  Using `strace` and `/proc/*/fd`, I could see that the PHP application was blocked reading from wkhtmltopdf's stdout, and wkhtmltopdf was blocked writing to its stderr.  Looking at [the PHP code](https://github.com/aur1mas/Wkhtmltopdf/blob/49a2619d78af36c99c3bd1e21904595e65df0a28/Wkhtmltopdf.php#L176-L180) shows that nothing will be read from wkhtmltopdf's stderr until stdout has been read completely.  I suspect [the pipe buffer](http://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer) filled up, so that `write(stderr, ...)` would not return until the buffer was consumed, but since the PHP is blocked reading stdout, the buffer will never be emptied.  This wouldn't happen with every PDF since there is a buffer, but presumably longer PDFs generate more output on stderr and hit the buffer limit.

I think one solution would be to use `stream_select()` to effectively read from both stdout and stderr at the same time.  The input should probably be written the same way, as I'd imagine the output buffers could also fill up before the input is completely written.  In my case my input is a file, so I don't know.

This may be the issue in #18, but there's not enough information to know.

**Comment by francoisjacquet** [comment]
Hello @scintill @aur1mas 

PR #26  was ported to RosarioSIS v5.6.4: https://github.com/francoisjacquet/rosariosis/commit/193606c671cbdfa640d764a265956a3188a7fe66

This fixes a crash when printing large PDF on Linux.
But this produces a crash on Windows (PHP 5.4.45), no matter the size of the PDF.

A quick fix (old exec code is used instead if OS is Windows) has been added to v5.7.3: https://github.com/francoisjacquet/rosariosis/commit/5395172d8646613b1f2914b1e053c3f960707b38
