### ISSUE TITLE
Message: Path to directory where to store files is not set

### ISSUE THREAD

**Issue by roopeshm456** [aur1mas/Wkhtmltopdf#33]
i used wkhtmltopdf in codeigniter framework. but it raises `Message: Path to directory where to store files is not set` error

**Comment by aur1mas** [comment]
@roopeshm456 as exception states, you should provide a path where to store files. See error: https://github.com/aur1mas/Wkhtmltopdf/blob/master/Wkhtmltopdf.php#L127
